# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$all"""
#right_format = """$git_branch$git_status$cmd_duration$directory"""


add_newline = true

[time]
disabled = true
use_12hr = true
format = '[ $time]($style) '
style = 'bold italic bright-black'

# [awsOLD]
# format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
# force_display = true
# style = 'bold blue'

[aws]
format = '\[[$symbol $profile]($style)\]'
style = 'bold blue'
symbol = '🅰'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'
[docker_context]
disabled = true
format = '\[[$symbol$context]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
 # format = '([\[$all_status$ahead_behind\]]($style))'
format = '([\[$staged$modified$untracked$renamed$deleted$ahead_behind\]]($style))'


[golang]
format = '\[[$symbol($version)]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[python]
# format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
format = '\[[ ${version}\($virtualenv\)]($style)\]'
style = 'yellow'

[ruby]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[sudo]
disabled = false
symbol = ' 👩 '
style = 'green'
# format = '\[[as $symbol]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[username]
disabled = true
format = '\[[$user]($style)\]'

